### ISSUE TITLE
CPQ17 Trading Losses - incomplete error message

### ISSUE THREAD

**Issue by honir** [hmrc/ct-calculations#429]
There's an issue with the completion of Trading Losses - Losses from an earlier period.
( .../computations/trading-losses/previous-current )

Steps to reproduce:

Enter values as follows:
CPQ17 Yes
CP281 10000
CP281a  7500
CP288a  7500
CP281b  2500
CP997  0
CP288b  2500

Press "Save and continue" and an error is returned (see screengrab below):

"There is a problem with the form
Answer to continue
Answer to continue"

but there is no text to the message. i.e. "Answer" what?

Hovering over the links suggests 
computations/trading-losses/previous-current#CP283a
and
computations/trading-losses/previous-current#CP283b

but these boxes do not appear on this screen.

The error message seems spurious. But the form will not submit.

![unknown_error](https://user-images.githubusercontent.com/5416674/54603975-8b2db600-4a3d-11e9-8591-179031edbb36.jpg)

**Comment by richardb1956** [comment]
anyone solve this problem?

**Comment by accshxp** [comment]
I have the same problem! Cannot figure it out, and no-one at HMRC seems to be able to help.

**Comment by honir** [comment]
I guess the answer is here:

> Losses brought forward from earlier periods of account
>  
> The service does not provide a facility to maintain a record of losses brought forward from an earlier period and carried forward to later periods unless there are profits in the period against which some or all of the losses can be claimed. A record of losses should be kept in the company’s own records.

So you can only record losses c/f when the current period shows a profit.

(But note a zero value is allowed if you do not want to offset your b/f losses against current period profits for any reason).


The error message should be fixed though. Or even better don't even offer this form (CPQ17) if there aren't any profits in the current period.

**Comment by liquidarmour** [comment]
If this is still an issue for you you should submit feedback via the links within the application. Unfortunately there is no one monitoring these issues. Before you ask, I am no longer involved in this project.
